/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kivaryhma;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.PrintWriter;
import java.io.UnsupportedEncodingException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author toffe
 */
public class Form extends javax.swing.JFrame implements ActionListener {

    private Controller controller;
    private JLabel[] labels = new JLabel[10];
    private JTextField[] articleFields = new JTextField[10];
    private JTextField[] bookFields = new JTextField[11];
    private JTextField[] inproceedingsFields = new JTextField[14];
    private JFileChooser fileChooser = new JFileChooser();
    /**
     * Creates new form Frame2
     */
    public Form() {
        //Luodaan komponentit
        initComponents();

        //Actionlisteneri submit napille
        submitArticle.addActionListener(this);

        //Kaikki tekstikentät fields-listoihin helpompaa käsittelyä varten
        gatherArticleTextFields();
        gatherBookTextFields();
        gatherInproceedingsTextFields();

        //Poistetaan placeholderit jotka tuli netbeansin lomakkeenluojan mukana
        String[] temp = new String[0];
        jList1.setListData(temp);
    }

    public void submitArticleForm() {
        //Lähetetään lista controllerille
        controller.sendArticleFormParameters(gatherValues(articleFields));
    }
    
    public void submitBookForm() {
        //Lähetetään kontrollerimetodille tavarat bookformista
        controller.sendBookFormParameters(gatherValues(bookFields));
    }
    
    public void submitInproceedingsForm() {
        //lähetetään kontrollerimetodille tavarat inproceedings formista
        controller.sendInproceedingsFormParameters(gatherValues(inproceedingsFields));
    }
    public void saveToFile(){
        
        try {
             ArrayList<Entry> entries = new ArrayList<Entry>(controller.getEntries());
            this.fileChooser.setCurrentDirectory(new File("."));
            int retrieval = this.fileChooser.showSaveDialog(rootPane);
            
            if(retrieval== JFileChooser.APPROVE_OPTION){
                PrintWriter writer = null;
                writer = new PrintWriter(fileChooser.getSelectedFile()+".bib");
                for (Entry entry : entries) {
                    writer.println(entry.toBibtex());
                }
                writer.close();
            }
             
        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(rootPane,"Jokin meni pieleen","Error",JOptionPane.ERROR_MESSAGE);
        }
    } 
    //Kerätään arvot tekstikentistä
    public String[] gatherValues(JTextField[] fields) {
        String[] values = new String[fields.length];
        for(int i = 0; i < fields.length; i++) {
            values[i] = fields[i].getText();
        }
        return values;
    }

    //Päivitetään listanäkymä
    public void updateList() {
        ArrayList<String> data = new ArrayList<String>();
        for (Entry entry : controller.getEntries()) {
            data.add(entry.getAuthor() + " - " + entry.getYear() + " - " + entry.getTitle());
        }
        jList1.setListData(data.toArray());
    }

    public void registerController(Controller controller) {
        this.controller = controller;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        inproceedingsPane = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        articleAuthor = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        articleTitle = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        articleJournal = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        articleYea = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        articleVolume = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        articleNumber = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        articlePages = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        articleMonth = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        articleNote = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        articleKey = new javax.swing.JTextField();
        submitArticle = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        bookAuthor = new javax.swing.JTextField();
        bookTitle = new javax.swing.JTextField();
        bookPublisher = new javax.swing.JTextField();
        bookYear = new javax.swing.JTextField();
        bookVolume = new javax.swing.JTextField();
        bookSeries = new javax.swing.JTextField();
        bookAddress = new javax.swing.JTextField();
        bookEdition = new javax.swing.JTextField();
        bookMonth = new javax.swing.JTextField();
        bookNote = new javax.swing.JTextField();
        bookKey = new javax.swing.JTextField();
        bookSubmit = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        inproceedingsAuthor = new javax.swing.JTextField();
        inproceedingsTitle = new javax.swing.JTextField();
        inproceedingsBooktitle = new javax.swing.JTextField();
        inproceedingsYear = new javax.swing.JTextField();
        inproceedingsEditor = new javax.swing.JTextField();
        inproceedingsVolume = new javax.swing.JTextField();
        inproceedingsSeries = new javax.swing.JTextField();
        inproceedingsPages = new javax.swing.JTextField();
        inproceedingsAddress = new javax.swing.JTextField();
        inproceedingsMonth = new javax.swing.JTextField();
        inproceedingsOrganization = new javax.swing.JTextField();
        inproceedingsPublisher = new javax.swing.JTextField();
        inproceedingsNote = new javax.swing.JTextField();
        inproceedingsKey = new javax.swing.JTextField();
        submitInproceedings = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jButton1 = new javax.swing.JButton();
        virheViesti = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 489, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel1.setText("Author *");

        jLabel3.setText("Journal *");

        articleTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                articleTitleActionPerformed(evt);
            }
        });

        jLabel2.setText("Title *");

        jLabel4.setText("Year *");

        jLabel5.setText("Volume *");

        jLabel6.setText("Number");

        jLabel7.setText("Pages");

        jLabel8.setText("Month");

        jLabel9.setText("Note");

        jLabel10.setText("Key");

        submitArticle.setText("Submit Article");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(articleJournal)
                            .addComponent(articleAuthor)
                            .addComponent(articleTitle, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(articleNumber)
                            .addComponent(articleVolume)
                            .addComponent(articleYea, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(articleNote)
                            .addComponent(articlePages)
                            .addComponent(articleMonth)
                            .addComponent(articleKey))
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(submitArticle)
                        .addGap(0, 150, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(articleAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(articleJournal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(articleTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(articleYea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(articleVolume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(articleNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(articlePages, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(articleMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(articleNote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(articleKey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(30, 30, 30)
                .addComponent(submitArticle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        inproceedingsPane.addTab("Article", jPanel2);

        jLabel11.setText("Author *");

        jLabel12.setText("Title *");

        jLabel13.setText("Publisher *");

        jLabel14.setText("Year *");

        jLabel15.setText("Volume");

        jLabel16.setText("Series");

        jLabel17.setText("Address");

        jLabel18.setText("Edition");

        jLabel19.setText("Month");

        jLabel20.setText("Note");

        jLabel21.setText("Key");

        bookTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookTitleActionPerformed(evt);
            }
        });

        bookSeries.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookSeriesActionPerformed(evt);
            }
        });

        bookNote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookNoteActionPerformed(evt);
            }
        });

        bookKey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookKeyActionPerformed(evt);
            }
        });

        bookSubmit.setText("Submit Book");
        bookSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookSubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bookTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                            .addComponent(bookAuthor)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bookPublisher)
                            .addComponent(bookYear)
                            .addComponent(bookVolume)
                            .addComponent(bookSeries)
                            .addComponent(bookAddress)
                            .addComponent(bookEdition)
                            .addComponent(bookMonth)
                            .addComponent(bookNote)
                            .addComponent(bookKey)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(jLabel20)
                            .addComponent(bookSubmit))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(bookAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(bookTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(bookPublisher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(bookYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(bookVolume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(bookSeries, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(bookAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(bookEdition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(bookMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(bookNote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(bookKey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(bookSubmit)
                .addContainerGap(105, Short.MAX_VALUE))
        );

        inproceedingsPane.addTab("Book", jPanel3);

        jLabel22.setText("Author  *");

        jLabel23.setText("Title *");

        jLabel24.setText("Booktitle *");

        jLabel25.setText("Year *");

        jLabel26.setText("Editor");

        jLabel27.setText("Volume");

        jLabel28.setText("Series");

        jLabel29.setText("Pages");

        jLabel30.setText("Address");

        jLabel31.setText("Month");

        jLabel32.setText("Organization");

        jLabel33.setText("Publisher");

        jLabel34.setText("Note");

        jLabel35.setText("Key");

        inproceedingsYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inproceedingsYearActionPerformed(evt);
            }
        });

        submitInproceedings.setText("Submit Inproceedings");
        submitInproceedings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitInproceedingsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25)
                            .addComponent(jLabel26)
                            .addComponent(jLabel30)
                            .addComponent(jLabel31)
                            .addComponent(jLabel32)
                            .addComponent(jLabel33)
                            .addComponent(jLabel34)
                            .addComponent(jLabel35)
                            .addComponent(jLabel27)
                            .addComponent(jLabel28)
                            .addComponent(jLabel29))
                        .addGap(3, 3, 3)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inproceedingsOrganization, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(inproceedingsMonth, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(inproceedingsAddress, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(inproceedingsPages, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(inproceedingsSeries, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(inproceedingsVolume, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(inproceedingsEditor, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(inproceedingsYear)
                            .addComponent(inproceedingsPublisher)
                            .addComponent(inproceedingsNote)
                            .addComponent(inproceedingsKey)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addComponent(jLabel23)
                            .addComponent(jLabel24))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inproceedingsBooktitle)
                            .addComponent(inproceedingsTitle)
                            .addComponent(inproceedingsAuthor)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(submitInproceedings)
                        .addGap(0, 84, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(inproceedingsAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(inproceedingsTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inproceedingsBooktitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inproceedingsYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inproceedingsEditor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inproceedingsVolume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inproceedingsSeries, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inproceedingsPages, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inproceedingsAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inproceedingsMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inproceedingsOrganization, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inproceedingsPublisher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel33))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inproceedingsNote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel34))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inproceedingsKey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel35))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(submitInproceedings)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        inproceedingsPane.addTab("Inproceedings", jPanel4);

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jButton1.setText("Bibtex");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bibtexButton(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(inproceedingsPane, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(virheViesti))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(virheViesti)
                        .addGap(35, 35, 35)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addComponent(inproceedingsPane, javax.swing.GroupLayout.PREFERRED_SIZE, 571, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public JFileChooser getFileChooser(){
        return this.fileChooser;
    }
    private void bibtexButton(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bibtexButton

        this.saveToFile();
    }//GEN-LAST:event_bibtexButton
    
    private void articleTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_articleTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_articleTitleActionPerformed

    private void bookTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookTitleActionPerformed

    private void bookSeriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookSeriesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookSeriesActionPerformed

    private void bookNoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookNoteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookNoteActionPerformed

    private void bookKeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookKeyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookKeyActionPerformed

    private void inproceedingsYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inproceedingsYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inproceedingsYearActionPerformed

    private void bookSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookSubmitActionPerformed
        submitBookForm();
        updateList();
        emptyReferenceTextFields(bookFields);
    }//GEN-LAST:event_bookSubmitActionPerformed

    private void submitInproceedingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitInproceedingsActionPerformed
        submitInproceedingsForm();
        updateList();
        emptyReferenceTextFields(inproceedingsFields);
    }//GEN-LAST:event_submitInproceedingsActionPerformed

    /**
     * @param args the command line arguments
     */
    public void display() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField articleAuthor;
    private javax.swing.JTextField articleJournal;
    private javax.swing.JTextField articleKey;
    private javax.swing.JTextField articleMonth;
    private javax.swing.JTextField articleNote;
    private javax.swing.JTextField articleNumber;
    private javax.swing.JTextField articlePages;
    private javax.swing.JTextField articleTitle;
    private javax.swing.JTextField articleVolume;
    private javax.swing.JTextField articleYea;
    private javax.swing.JTextField bookAddress;
    private javax.swing.JTextField bookAuthor;
    private javax.swing.JTextField bookEdition;
    private javax.swing.JTextField bookKey;
    private javax.swing.JTextField bookMonth;
    private javax.swing.JTextField bookNote;
    private javax.swing.JTextField bookPublisher;
    private javax.swing.JTextField bookSeries;
    private javax.swing.JButton bookSubmit;
    private javax.swing.JTextField bookTitle;
    private javax.swing.JTextField bookVolume;
    private javax.swing.JTextField bookYear;
    private javax.swing.JTextField inproceedingsAddress;
    private javax.swing.JTextField inproceedingsAuthor;
    private javax.swing.JTextField inproceedingsBooktitle;
    private javax.swing.JTextField inproceedingsEditor;
    private javax.swing.JTextField inproceedingsKey;
    private javax.swing.JTextField inproceedingsMonth;
    private javax.swing.JTextField inproceedingsNote;
    private javax.swing.JTextField inproceedingsOrganization;
    private javax.swing.JTextField inproceedingsPages;
    private javax.swing.JTabbedPane inproceedingsPane;
    private javax.swing.JTextField inproceedingsPublisher;
    private javax.swing.JTextField inproceedingsSeries;
    private javax.swing.JTextField inproceedingsTitle;
    private javax.swing.JTextField inproceedingsVolume;
    private javax.swing.JTextField inproceedingsYear;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton submitArticle;
    private javax.swing.JButton submitInproceedings;
    private javax.swing.JLabel virheViesti;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent ae) {
        //Napinpainallus submittaa formin
        submitArticleForm();
        //Päivitetään lista sivussa ja tyhjennetään tekstikentät
        emptyReferenceTextFields(articleFields);
        updateList();
    }
    
    public void gatherBookTextFields() {
        bookFields[0] = bookAuthor;
        bookFields[1] = bookTitle;
        bookFields[2] = bookPublisher;
        bookFields[3] = bookYear;
        bookFields[4] = bookVolume;
        bookFields[5] = bookSeries;
        bookFields[6] = bookAddress;
        bookFields[7] = bookEdition;
        bookFields[8] = bookMonth;
        bookFields[9] = bookNote;
        bookFields[10] = bookKey;
    }

    public void gatherArticleTextFields() {
        articleFields[0] = articleAuthor;
        articleFields[1] = articleJournal;
        articleFields[2] = articleTitle;
        articleFields[3] = articleYea;
        articleFields[4] = articleVolume;
        articleFields[5] = articleNumber;
        articleFields[6] = articlePages;
        articleFields[7] = articleMonth;
        articleFields[8] = articleNote;
        articleFields[9] = articleKey;
    }
    
    public void gatherInproceedingsTextFields() {
        inproceedingsFields[0] = inproceedingsAuthor;
        inproceedingsFields[1] = inproceedingsTitle;
        inproceedingsFields[2] = inproceedingsBooktitle;
        inproceedingsFields[3] = inproceedingsYear;
        inproceedingsFields[4] = inproceedingsEditor;
        inproceedingsFields[5] = inproceedingsVolume;
        inproceedingsFields[6] = inproceedingsSeries;
        inproceedingsFields[7] = inproceedingsPages;
        inproceedingsFields[8] = inproceedingsAddress;
        inproceedingsFields[9] = inproceedingsMonth;
        inproceedingsFields[10] = inproceedingsOrganization;
        inproceedingsFields[11] = inproceedingsPublisher;
        inproceedingsFields[12] = inproceedingsNote;
        inproceedingsFields[13] = inproceedingsKey;
    }

    public JTextField[] getBookFields() {
        return bookFields;
    }
    public JButton getJButton1(){
        return this.jButton1;
    }
    public JTextField[] getInproceedingsFields() {
        return inproceedingsFields;
    }
    
    public JTextField[] getArticleFields() {
        return articleFields;
    }

    public JList getReferenceList() {
        return jList1;
    }

    //metodi tyhjentää jonkun lomakkeen tekstikentät
    public void emptyReferenceTextFields(JTextField[] fields) {
        for(int i = 0; i < fields.length; i++) {
            fields[i].setText("");
        }
    } 
    
    public void setVirheViesti(String viesti) {
        virheViesti.setText(viesti);
    }

    public JLabel getVirheViesti() {
        return virheViesti;
    }
}
